/'
    Ing. Tirso Martínez Reyes
    Universidad Internacional de la Rioja
    Programación en el servidor
    Enero 2022
'/

@startuml SECRET_TODO_USECASES
left to right direction

title Diagrama de Casos de uso

rectangle Navegador {
    actor "Usuario" as U
}

rectangle Servidor {
    usecase "Visitar Página de Inicio" as UC_home
    usecase "Crear un Secret To-Do" as UC_createToDo
    usecase "Acceder a un Secret To-Do" as UC_getToDo
    usecase "Cerrar un Secret To-Do" as UC_closeToDo
    usecase "Listar items del Secret To-Do" as UC_listToDo
    usecase "Agregar un Item al Secret To-Do" as UC_addItem
    usecase "Eliminar un Item del Secret To-Do" as UC_removeItem
    usecase "Actualizar un Item del Secret To-Do" as UC_updateItem

    U --> UC_home
    U --> UC_createToDo
    U --> UC_getToDo
    U --> UC_closeToDo
    U --> UC_listToDo
    U --> UC_addItem
    U --> UC_removeItem
    U --> UC_updateItem
}
@enduml

@startuml SECRET_TODO_FLOW
scale 2
title Diagrama de Actividad de usuario

start
:Accede a la página de inicio;
fork
:Crear Secret To-Do;
fork again
:Acceder a un Secret To-Do;
end fork
fork
:Listar items en Secret To-Do;
fork again
:Agregar un Item al Secret To-Do;
fork again
:Eliminar un Item del Secret To-Do;
fork again
:Actualizar un Item del Secret To-Do;
end fork
:Cerrar un Secret To-Do;
stop
@enduml

@startuml SECRET_TODO_ENTITIES
title Diagrama de Clases

class ToDo{
    Integer id
    String label
    String userPassPhrase
    String systemPassPhrase
    Item[] items
    AccessToken accessToken
}

class Item{
    Integer Id
    Boolean isDone
    String label
}

class AccessToken{    
    String accessToken
    'Integer startTime
    'Integer endTime
    Integer toDo
}

class Log{
    Integer id
    Integer time
    String  target
    String  action
    String  data
}


ToDo -l- Item : tiene 0 o más >
ToDo -r- AccessToken : Tiene un >

Log -u- ToDo : Registra <
Log -u- Item : Registra <
Log -u- AccessToken : Registra <
@enduml